#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-qc

set -e  

dwi=$(jq -r .dwi config.json)
bval=$(jq -r .bvals config.json)
bvec=$(jq -r .bvecs config.json)
# create symbolic link here
source=${dwi##*/}
ln -sf ${dwi} ${source}

# if SRC file is assigned use it instead
src=$(jq -r .src config.json)
if [ -f "$src" ]
then 
  source=${src##*/}
  ln -sf ${src} ${source}
  bval="";
  bvec="";
fi

# setup bval bvec parameters
if [ ! -z "$bval" ]; then bval="--bval=${bval}"; fi
if [ ! -z "$bvec" ]; then bvec="--bvec=${bvec}"; fi

time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=qc --source=${source} ${bval} ${bvec} 
echo "{\"datatype_tags\": [\"qc\"]}" > product.json

# move file to stat folder
mkdir -p stat
mv *.qc.txt stat/tractmeasure
